### PR TITLE
Consume events from the input queue.

### LINKED ISSUE #190: [Bug]: ANR after pressing volume up/down
### What happened?

5 seconds after pressing volume up/volume down, apps will ANR because we're not handling events from the InputQueue. This also results in the volume buttons not actually changing the volume, because the system is waiting for us to say whether or not we're handling them.

### Version

latest

### In which Hotham component are you seeing the problem on?

Core

### What VR System are you seeing the problem on?

Quest-2

### What OS are you seeing the problem on?

_No response_

### Relevant log output

```shell
04-21 23:43:05.724  1076  1178 E ActivityManager: ANR in rust.crab_saber (rust.crab_saber/android.app.NativeActivity)
04-21 23:43:05.724  1076  1178 E ActivityManager: PID: 10721
04-21 23:43:05.724  1076  1178 E ActivityManager: Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.)
04-21 23:43:05.724  1076  1178 E ActivityManager: Parent: rust.crab_saber/android.app.NativeActivity
04-21 23:43:05.724  1076  1178 E ActivityManager: Load: 5.57 / 2.41 / 1.71
```

### PR DESCRIPTION
**Pull request by jmgao**
Pressing volume up/down shows up as events in AInputQueue, and the
system expects us to consume them within a reasonable amount of time,
under penalty of ANR.

Fixes #190.

### CODE REVIEW

**Comment by kanerogers** [comment]
This looks good to me from a code soundness standpoint but I'm unable to verify it on a physical device.

@sinoth are you able to review this when you get a moment? 😄

**Comment by sinoth** [comment]
Sorry but I can't verify this due to what seems to be an unrelated error that was introduced in the validation layer changes:

```
   Compiling hotham v0.1.1 (F:\Rust\hotham\hotham)
error[E0599]: no method named `push` found for mutable reference `&mut [CString]` in the current scope
    --> hotham\src\resources\vulkan_context.rs:1026:21
     |
1026 |     extension_names.push(CString::new("VK_KHR_multiview").unwrap());
     |                     ^^^^ method not found in `&mut [CString]`
```

@kanerogers I could use some guidance here -- I'll hit you up on the Discord.

**Comment by jmgao** [comment]
> Sorry but I can't verify this due to what seems to be an unrelated error that was introduced in the validation layer changes:
> 
> ```
>    Compiling hotham v0.1.1 (F:\Rust\hotham\hotham)
> error[E0599]: no method named `push` found for mutable reference `&mut [CString]` in the current scope
>     --> hotham\src\resources\vulkan_context.rs:1026:21
>      |
> 1026 |     extension_names.push(CString::new("VK_KHR_multiview").unwrap());
>      |                     ^^^^ method not found in `&mut [CString]`
> ```
> 
> @kanerogers I could use some guidance here -- I'll hit you up on the Discord.

https://github.com/leetvr/hotham/pull/197/commits/fea7f9b1257f80181404a28936d858d78abd3439 should fix it, I'll merge that patch into this branch.

**Review by sinoth — APPROVED** [review]
Works as expected -- volume up/down are responsive in Crab Saber on my Quest 2.

**Pull request merged**
