### PR TITLE
Add dual licence

### LINKED ISSUE #144: Add dual licence

### PR DESCRIPTION
**Pull request by kanerogers**
Fixes #144

### CODE REVIEW

**Comment by davidkuhta** [comment]
@kanerogers Probably good practice to have @jam1garner @pierrelarger @rezural backdate approve their contributions, by commenting in this thread with:

`I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.`

akin to how Bevy handle that:

https://github.com/bevyengine/bevy/issues/2373

**Comment by jam1garner** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by rezural** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by kanerogers** [comment]
Thanks, everyone!

**Pull request merged**
